max_steps = 1500

[wandb]
project = "gsm8k-rl"
name = "gsm8k-run-2"

[deployment]
num_train_gpus = 1
num_infer_gpus = 1

[model]
name = "Qwen/Qwen2.5-0.5B-Instruct"

[trainer.model]
impl = "auto"

[trainer.model.ac]
freq = 1

[trainer.model.lora]
rank = 32
alpha = 64

[trainer.optim]
lr = 1e-5

[orchestrator]
batch_size = 64
group_size = 8
seq_len = 2048

[[orchestrator.train.env]]
id = "gsm8k"

[orchestrator.eval]
interval = 100

[[orchestrator.eval.env]]
id = "gsm8k"
name = "gsm8k-eval"

[orchestrator.renderer]
name = "default"
reasoning_parser = "think"

[inference.model]
max_model_len = 2048
